knp_paginator:
  page_range: 5 # nombre de liens numériques affichés
  default_options:
    page_name: page # nom du paramètre 'page' passé dans l’URL
    sort_field_name: sort # nom du paramètre 'tri' passé dans l’URL
    sort_direction_name: direction # nom du paramètre 'direction' passé dans l’URL
    distinct: true # résultats distincts (pour des requêtes GROUP BY)
    filter_field_name: filterField # nom du paramètre champ filtré
    filter_value_name: filterValue # nom du paramètre valeur filtrée
  template:
    pagination: "@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig"
    sortable: "@KnpPaginator/Pagination/sortable_link.html.twig"
    filtration: "@KnpPaginator/Pagination/filtration.html.twig"
